# Site settings
baseurl: "" # root of your GitHub Pages site (username.github.io)

# Build settings
markdown: kramdown
plugins:
  - jekyll-email-protect

timezone: Asia/Shanghai

collections:
  - publications
  - news
  - showcase
  - posts
